### ISSUE TITLE
The "Commons Clause" of your license defeats apache 2.0

### ISSUE THREAD

**Issue by RandalSchwartz** [nfriend/inspiral#1]
You should not claim Apache 2 if you're not compatible with it.  Please remove your "sell" clause.

**Comment by nfriend** [comment]
@RandalSchwartz Thanks for this! Looking at the license again, I think you're right. The license is _not_ Apache 2.0, and the license text should make that clear. I won't be removing the "sell" clause, but I do think the license could be more clear about this.

I've created https://gitlab.com/nfriend/inspiral/-/issues/93 so I don't lose track of this.

Thanks for the feedback!

**Comment by nfriend** [comment]
License removed in https://github.com/nfriend/inspiral/commit/5f22a03c10837f6bfcdc2d52876b6817b6844a55. This will hopefully clear up any confusion caused by the Commons Clause. This app is "source available", but it is not "open source". By removing the license, I'm falling back to the default protections described here: https://opensource.stackexchange.com/a/1721.
